### ISSUE TITLE
Host Machine Unable To Trigger Zerotier One localhost:9993 API? Now Have Connection Refused Error

### ISSUE THREAD

**Issue by jerrychong25** [zyclonite/zerotier-docker#17]
Hi all,

I would like to trigger Zerotier localhost:9993 API from host machine (Where it run docker compose up command) as mentioned in https://docs.zerotier.com/self-hosting/network-controllers/#authorize-a-member.

Unfortunately, it have this error when running the command on the host machine:
```
ubuntu@host-machine:~/linkup-vpn-server/backup$ curl -X POST "http://localhost:9993/controller/network/XXXXXXXXXXXXXXXX/member/XXXXXXXXXX" -H "X-ZT1-AUTH: AUTH_STRING_HERE" -d '{"authorized": true}'

curl: (7) Failed to connect to localhost port 9993 after 0 ms: Connection refused
```

Here is my docker compose codes:
```
  zerotier:
    image: zyclonite/zerotier:1.10.1
    container_name: zu-controller
    restart: unless-stopped
    volumes:
      - controller_data:/var/lib/zerotier-one
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
    expose:
      - "9993/tcp"
    ports:
      - "9993:9993/udp"
```

Any solution to solve?

I've tried use following solutions to fix it:
- sudo ufw allow 9993/tcp
- echo "{\"settings\": {\"portMappingEnabled\": true,\"softwareUpdate\": \"disable\",\"allowManagementFrom\": [\"0.0.0.0/0\"]}}" > /var/lib/zerotier-one/local.conf

Unfortunately, both does not solved my issues either.

Thank you.

**Comment by zyclonite** [comment]
maybe try

```
  zerotier:
    image: zyclonite/zerotier:1.10.1
    container_name: zu-controller
    restart: unless-stopped
    volumes:
      - controller_data:/var/lib/zerotier-one
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
    ports:
      - "9993:9993/tcp"
      - "9993:9993/udp"
```

if i run `docker run -d --name zu-controller -p 9993:9993/udp -p 9993:9993/tcp -e ZT_OVERRIDE_LOCAL_CONF=true -e ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0 zyclonite/zerotier:1.10.1` directly, everything looks fine

you can double check if the port is listening with `netstat -an | grep 9993`
