### ISSUE TITLE
Wrong date/time in docker container

### ISSUE THREAD

**Issue by ToonMeynen** [zyclonite/zerotier-docker#23]
Hello, 
I can't join my network. I get following error. 
`zerotier-one | connect: Operation timed out`
I believe that part of the problem is that my clock/date is incorrect in the docker container. 

docker-compose file: 
```
version: '3'
services:
  zerotier:
    image: "zyclonite/zerotier:router"
    container_name: zerotier-one
    devices:
      - /dev/net/tun
    network_mode: host
    volumes:
      - '/var/lib/zerotier-one:/var/lib/zerotier-one'
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    restart: unless-stopped
    environment:
      - TZ=Europe/Brussels
      - PUID=999
      - PGID=994
      - ZEROTIER_ONE_LOCAL_PHYS=eth0
      - ZEROTIER_ONE_USE_IPTABLES_NFT=false
      - ZEROTIER_ONE_GATEWAY_MODE=inbound
      - ZEROTIER_ONE_NETWORK_IDS=MYIDXXXXXX

```

Logs when I run the container 
```
pi@raspberrypi:~/ZeroTier $ docker-compose up
zerotier-one is up-to-date
Attaching to zerotier-one
zerotier-one | changed ownership of '/var/lib/zerotier-one/peers.d/778cde7190.peer' to 999:994
zerotier-one | changed ownership of '/var/lib/zerotier-one/peers.d/cafe9efeb9.peer' to 999:994
zerotier-one | changed ownership of '/var/lib/zerotier-one/peers.d/62f865ae71.peer' to 999:994
zerotier-one | changed ownership of '/var/lib/zerotier-one/peers.d/cafe04eba9.peer' to 999:994
zerotier-one | Sun Jan  0 00:00:00  1900 - launching ZeroTier-One in routing mode
zerotier-one | adding iptables rules for inbound traffic (ZeroTier to local interfaces eth0)
zerotier-one | Sun Jan  0 00:00:00  1900 - ZeroTier daemon is running as process 16
zerotier-one | connect: Operation timed out
zerotier-one | connect: Operation timed out
zerotier-one | connect: Operation timed out
```
