### ISSUE TITLE
Unable to bridge

### ISSUE THREAD

**Issue by outofsight** [zyclonite/zerotier-docker#9]
Thanks for your work, but unfortunately I'm not able to use it.
I'm running Proxmox VE on a minipc and a Debian VM with docker.
I'm trying to run this zerotier container under this docker instance.
I would like to setup a bridge to access all hosts in my LAN, on the same docker instance, or on other VM, or on other physical devices.

With the help of portainer I created and started a stack with te following compose file.

```
version: '3'
services:
  zerotier:
    container_name: zerotier-bridge
    image: zyclonite/zerotier:bridge-latest
    network_mode: host
    volumes:
      - '/data/zerotier:/var/lib/zerotier-one'
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
```

I made the necessary steps to join a ZeroTier private network (with assigned IP range non conflicting with the one of LAN DHCP server, and with appropriate managed route) and authorized the bridge (allowing bridging) and all clients (mobile phone for test).

But from my phone (on mobile data) I'm unable to reach any LAN host and also the bridge itself (tried to ping, and to access other services on the same VM/docker instance).

From what I understand the ethernet interface ("ens18") get the ip address from LAN DHCP server as usual, and the zt interface ("ztbto2poqh") get the expected ip address as configured in my.zerotier.com.

But I don't know how to further investigate.

Any idea?
